name: .NET Core

on:
  push:
    branches: [ rewrite ]
  pull_request:
    branches: [ rewrite ]

jobs:
  build:
    strategy:
      matrix:
        runtime: ['ubuntu-x64', 'win-x64', 'osx-x64']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Install dependencies
      run: dotnet restore
    - name: Build ${{ matrix.runtime }}
      run: dotnet publish -r ${{ matrix.runtime }} -c Release
    - name: Artifact Upload ${{ matrix.runtime }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.runtime }}
        path: QuestPatcher/bin/Release/net5.0/${{ matrix.runtime }}/publish/