name: Windows Installer

on: [push]

jobs:
  build:
    name: Build installer on windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Download Inno Setup
      uses: suisei-cn/actions-download-file@v1
      with:
        url: wget https://jrsoftware.org/download.php/is.exe
        target: ../
    - name: Build QuestPatcher
      run: dotnet publish QuestPatcher/QuestPatcher.csproj -c Release -r win-x64
    - name: Install Inno Setup
      run: '"../is.exe" /VERYSILENT /NORESTART /ALLUSERS'
    - name: Compile Installer
      run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" /f installer/installer.iss'
    - name: Artifact Upload
      uses: actions/upload-artifact@v2
      with:
        name: QuestPatcher-windows.exe
        path: ./installer/QuestPatcher-windows.exe